apiRevision: edurata.io/v1
name: enrich-wef-config
title: Enrich config
description: fetching with the wayback machine old articles of wef, adding to json and then uploading to s3
interface:
  inputs:
    properties:
      cursor:
        type: string
        title: cursor
        description: if to start from a specific element in the array
        default: 0
      limit:
        type: number
        title: limit
        description: if to break after a specific number of elements processed
        default: 100
steps:
  get-config:
    source:
      repoUrl: https://github.com/Edurata/edurata-functions.git
      path: etl/extract/download-s3
    dependencies:
      AWS_ACCESS_KEY_ID: ${secrets.AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${secrets.AWS_SECRET_ACCESS_KEY}
      bucket_name: wef-images
      files:
        - key: people.json
  enrich-people:
    timeout: 7200
    source:
      repoUrl: https://github.com/juliandm/penetratethecabinet.git
      path: functions/scrape-people
      ref: master
    dependencies:
      file: ${get-config.files[0].path}
      cursor: ${inputs.cursor}
      OXYLABS_PASSWORD: ${secrets.OXYLABS_PASSWORD}
      limit: ${inputs.limit}
  upload-people:
    source:
      repoUrl: https://github.com/Edurata/edurata-functions.git
      path: etl/load/upload-s3
    dependencies:
      AWS_ACCESS_KEY_ID: ${secrets.AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${secrets.AWS_SECRET_ACCESS_KEY}
      bucket_name: wef-images
      files:
        - path: ${enrich-people.file}
          key: people.json
