apiRevision: edurata.io/v1
runtime: python3_8
interface:
  inputs:
    properties:
      file:
        type: file
      limit:
        type: number
        title: limit
        description: if to break after a specific number of elements processed
        default: 100
  outputs:
    properties:
      file:
        type: file
