apiRevision: edurata.io/v1
interface:
  inputs:
    properties:
      file:
        type: file
      cursor:
        type: string
        title: start from
        description: if to start from a specific element in the array
        default: 0
  outputs:
    properties:
      file:
        type: file
      cursor:
        type: string
        title: cursor
        description: if to start from a specific element in the array
        default: 0
