apiRevision: edurata.io/v1
runtime: python3_10
interface:
  inputs:
    properties:
      file:
        type: file
      limit:
        type: number
        title: limit
        description: if to break after a specific number of elements processed
        default: 100
      cursor:
        type: number
        title: cursor
        description: if to start from a specific element in the array
        default: 0
      OXYLABS_PASSWORD:
        type: env
        title: OXYLABS_PASSWORD
        description: password for oxylabs
  outputs:
    properties:
      file:
        type: file
