name: Upload to S3 Bucket
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      S3_BUCKET_NAME: penetratethecabinet.com
      AWS_DEFAULT_REGION: eu-central-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Sync files to S3 bucket
        run: |
          npm install
          npm run build
          # print the identity
          aws sts get-caller-identity
          aws s3 sync ./build s3://${{ env.S3_BUCKET_NAME }}
